backend:
  name: github
  repo: MrTang-Yuhan/my-webpage
  branch: main
  base_url: https://my-webpage-adu.pages.dev
  auth_endpoint: /api/auth

media_folder: src/images/uploads
public_folder: /images/uploads

publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: src/posts
    slug: "{{archive}}/{{slug}}"
    path: "{{slug}}/index"
    media_folder: img
    public_folder: ./img
    create: true
    extension: md
    format: frontmatter
    nested:
      depth: 10
      summary: "{{title}}"
      subfolders: true
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post.njk
      - label: Archive
        name: archive
        widget: select
        required: true
        options:
          - label: 模型并行
            value: mode-parallelism
          - label: 备忘录
            value: 备忘录
          - label: 互联网络
            value: interconnect
          - label: triosim模拟器
            value: triosim模拟器
        hint: Choose archive directory. Create a new one with New Archive, then refresh.
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Description
        name: description
        widget: string
        required: false
      - label: Tags
        name: tags
        widget: list
        default:
          - post
      - label: Body
        name: body
        widget: markdown
